{% if config.aotu_analytics %}
<script>
    (function(e,t,n,a,o,i,m){
    e.alogObjectName=o,e[o]=e[o]||function(){(e[o].q=e[o].q||[]).push(arguments)},e[o].l=e[o].l||+new Date,i=t.createElement(n),i.asyn=1,i.src=a,m=t.getElementsByTagName(n)[0],m.parentNode.insertBefore(i,m)
    })(window,document,"script","//wq.360buyimg.com/data/ppms/movie/atlogs.1.0.1.min.js","aotulog");
</script>
{% endif %}
