{% if config.aotu_analytics %}
<script>
    (function(h,g,c,e,f,d,b){h.alogObjectName=f;h[f]=h[f]||function(){(h[f].q=h[f].q||[]).push(arguments)};h[f].l=1*new Date();d=g.createElement(c),b=g.getElementsByTagName(c)[0];d.async=1;d.src=e;b.parentNode.insertBefore(d,b)})(window,document,"script","//wqs.jd.com/promote/quark/atlogs.2.0.min.js","ATlog");
    ATlog('init', {app_key: 'aotu-blog-aotu.io-011',clickEvents: true,mta: true})
</script>
{% endif %}
